# Define the NATO phonetic alphabet as a dictionary
nato_phonetic_alphabet = {
    'A': 'Alpha',
    'B': 'Bravo',
    'C': 'Charlie',
    'D': 'Delta',
    'E': 'Echo',
    'F': 'Foxtrot',
    'G': 'Golf',
    'H': 'Hotel',
    'I': 'India',
    'J': 'Juliet',
    'K': 'Kilo',
    'L': 'Lima',
    'M': 'Mike',
    'N': 'November',
    'O': 'Oscar',
    'P': 'Papa',
    'Q': 'Quebec',
    'R': 'Romeo',
    'S': 'Sierra',
    'T': 'Tango',
    'U': 'Uniform',
    'V': 'Victor',
    'W': 'Whiskey',
    'X': 'X-ray',
    'Y': 'Yankee',
    'Z': 'Zulu',
}

phonetic_symbols = {
    ' ': 'Space',
    '-': 'Dash',
    '.': 'Dot',
    '@': 'At',
    ',': 'Comma',
    '!': 'Exclamation mark',
    '?': 'Question mark',
    "'": 'Apostrophe',
    '"': 'Quotation mark',
    ':': 'Colon',
    ';': 'Semicolon',
    '(': 'Left parenthesis',
    ')': 'Right parenthesis',
    '[': 'Left bracket',
    ']': 'Right bracket',
    '{': 'Left brace',
    '}': 'Right brace',
    '<': 'Left angle bracket',
    '>': 'Right angle bracket',
    '/': 'Slash',
    '\\': 'Backslash',
    '|': 'Vertical bar',
    '#': 'Number sign',
    '$': 'Dollar sign',
    '%': 'Percent sign',
    '&': 'Ampersand',
    '*': 'Asterisk',
    '+': 'Plus sign',
    '=': 'Equal sign',
    '~': 'Tilde',
    '`': 'Backtick',
    '^': 'Caret',
    '_': 'Underscore'
}

nato_phonetic_numbers = {
    '0': "Zero",
    '1': "One",
    '2': "Two",
    '3': "Tree",
    '4': "Fower",
    '5': "Fife",
    '6': "Six",
    '7': "Seven",
    "8": "Eight",
    '9': "Niner"
}